/*

other example on mutating table USING DLETE CASCADE

*/

DROP table DPET1;

CREATE TABLE DPET1(
    DEPTNO NUMBER,
    DNAME VARCHAR2(100),
    constraint DPET1_PK PRIMARY KEY (DEPTNO)
);

INSERT INTO DPET1 (DEPTNO, DNAME) VALUES (1, 'HR DEPT');
INSERT INTO DPET1 (DEPTNO, DNAME) VALUES (2, 'PO DEPT');
COMMIT;

SELECT * FROM DPET1;

-------------------------------------

DROP TABLE EMP1;

CREATE TABLE EMP1(
    EMPID NUMBER PRIMARY KEY,
    ENAME VARCHAR2(100),
    DEPTNO NUMBER, 
    CONSTRAINT EMP1_FK FOREIGN KEY (DEPTNO) REFERENCES DPET1(DEPTNO) ON DELETE CASCADE
);

INSERT INTO EMP1 VALUES (1, 'khaled', '1');
INSERT INTO EMP1 VALUES (2, 'ayoub', '1');
INSERT INTO EMP1 VALUES (3, 'alae', '1');
INSERT INTO EMP1 VALUES (4, 'achraf', '2');
INSERT INTO EMP1 VALUES (5, 'rachid', '2');
COMMIT;

SELECT * FROM EMP1;

-------------------------

CREATE OR REPLACE TRIGGER DELETE_EMP
BEFORE DELETE ON EMP1
FOR EACH ROW
DECLARE
MINV NUMBER;
BEGIN
    SELECT MIN(EMPID) INTO MINV FROM EMP1;
END;

-------------------------

DELETE FROM DPET1 WHERE DEPTNO = 1;
-- tring delete on cascade and in the same time trying to read from the table